openapi: 3.0.0
info:
  title: User API
  description: API for managing user data
  version: 1.0.0

servers:
  - url: http://localhost

paths:
  /api/users/{id}:
    get:
      summary: Get user by ID
      description: Retrieve user information by user ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    format: email
                    example: johndoe@example.com
                  age:
                    type: integer
                    example: 30
                  created_at:
                    type: string
                    format: date-time
                    example: 2023-05-01T00:00:00Z
                  updated_at:
                    type: string
                    format: date-time
                    example: 2023-05-10T00:00:00Z
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
